"""add phone to leads

Revision ID: 161e4e756052
Revises: 1948a6858f40
Create Date: 2026-07-06 15:08:25.472056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '161e4e756052'
down_revision: Union[str, Sequence[str], None] = '1948a6858f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('phone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'phone')
    # ### end Alembic commands ###
